# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2d726fb1dc95703da03f2d9d4629735731d977043960a329e3ed901e13a1dbadab5f0fe9ba7effe9581ab18bbd7cad8fdeb170f28341568367831dece8efa9f

test:
  secret_key_base: 5a67e09cb67934ee8a8440c17632bf91a78650285331f9f28d7146373cb1d6879b7b282e5a62e878d64600cf52fd1eb0cace41a7effc1344acf3d38543a91a2a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
